### PR TITLE
Use haskell-ci

### PR DESCRIPTION
**Pull request by phadej**
On top of https://github.com/pcapriotti/optparse-applicative/pull/342

---

Temporarily disable 7.0 and 7.2 jobs, as there aren't
ansi-wl-pprint-0.6.8 with 7.0/7.2 support
https://matrix.hackage.haskell.org/#/package/ansi-wl-pprint
    
I'll add it back, as soon as
https://github.com/feuerbach/ansi-terminal/pull/82
is decided upon

### CODE REVIEW

**Comment by phadej** [comment]
@HuwCampbell I released new version of `ansi-wl-pprint` reinstating GHC-7.0 support.

I also noted there was `{-# ANN #-}` pragma for HLint. GHC loads interpreter for them, which is comparable to using `TemplateHaskell` ([GHC issue #13609](https://gitlab.haskell.org/ghc/ghc/issues/13609), [similar issue](https://github.com/bos/aeson/issues/654)  in `aeson`). I removed it, and added `.hlint.yaml`; which caused small cascade of changes:
- move sources to `src/`
- so we can `hlint` in CI
- without moving to `src/` we'd hlint the tests too, and there are some more warnings which I don't feel comfortable to clean up.

**Comment by hcampbell-tyro** [comment]
Is this running tests for GHC 8.8.1? QC is still failing no?

**Comment by phadej** [comment]
@hcampbell-tyro it does run tests

```
Test suite logged to: /tmp/dist-test.nq6a/dist-newstyle/build/x86_64-linux/ghc-8.8.0.20190424/optparse-applicative-0.14.3.0/t/tests/test/optparse-applicative-0.14.3.0-tests.log 
1 of 1 test suites (1 of 1 test cases) passed. 
```

---

`haskell-ci` uses [`head.hackage`](https://github.com/hvr/head.hackage) patches when building GHC head and alpha releases.

**Comment by HuwCampbell** [comment]
Thanks.

I'll look more into the haskell-ci script in the coming days, but it seems to cover our bases.

**Comment by HuwCampbell** [comment]
I'm now getting build failures on ghc-7.0.4. Care to assist?

**Comment by phadej** [comment]
Yes.

I can check on Monday

**Comment by phadej** [comment]
CI will be fixed by itself when https://github.com/nick8325/quickcheck/pull/262 is merged&released.

Until then you can either lift the requirement for using installed `random` https://github.com/haskell-CI/haskell-ci/blob/a517459b7a82ae70e0d08399a60871c3f0ec2d1d/cabal.haskell-ci#L39-L41, or disable running tests on GHC-7.0.4 https://github.com/haskell-CI/haskell-ci/blob/a517459b7a82ae70e0d08399a60871c3f0ec2d1d/cabal.haskell-ci#L15-L17

**Pull request merged**
