### PR TITLE
Add support for hanging usage overflow by a specified indent level.

### PR DESCRIPTION
**Pull request by newhoggy**
Improvement along the lines of https://github.com/pcapriotti/optparse-applicative/issues/423

### CODE REVIEW

**Comment by newhoggy** [comment]
Before:

```
Usage: cardano-cli transaction build-raw [--byron-era | --shelley-era |
                                           --allegra-era | --mary-era |
                                           --alonzo-era] (--tx-in TX-IN
                                         [--tx-in-script-file FILE
                                           [
                                             (--tx-in-datum-file FILE |
                                               --tx-in-datum-value JSON VALUE)
                                             (--tx-in-redeemer-file FILE |
                                               --tx-in-redeemer-value JSON VALUE)
                                             --tx-in-execution-units (INT, INT)]])
                                         [--tx-in-collateral TX-IN]
                                         [--tx-out ADDRESS VALUE
                                           [--tx-out-datum-hash HASH]]
                                         [--mint VALUE (--mint-script-file FILE
                                           [
                                             (--mint-redeemer-file FILE |
                                               --mint-redeemer-value JSON VALUE)
                                             --mint-execution-units (INT, INT)])]
                                         [--invalid-before SLOT]
                                         [--invalid-hereafter SLOT]
                                         [--fee LOVELACE]
                                         [--certificate-file CERTIFICATEFILE
                                           [--certificate-script-file FILE
                                             [
                                               (--certificate-redeemer-file FILE |

                                                 --certificate-redeemer-value JSON VALUE)
                                               --certificate-execution-units (INT, INT)]]]
                                         [--withdrawal WITHDRAWAL
                                           [--withdrawal-script-file FILE
                                             [
                                               (--withdrawal-redeemer-file FILE |

                                                 --withdrawal-redeemer-value JSON VALUE)
                                               --withdrawal-execution-units (INT, INT)]]]
                                         [--json-metadata-no-schema |
                                           --json-metadata-detailed-schema]
                                         [--auxiliary-script-file FILE]
                                         [--metadata-json-file FILE |
                                           --metadata-cbor-file FILE]
                                         [--genesis FILE |
                                           --protocol-params-file FILE]
                                         [--update-proposal-file FILE]
                                         --out-file FILE
```

After:

```
Usage: cardano-cli transaction build-raw
          [--byron-era | --shelley-era | --allegra-era | --mary-era |
            --alonzo-era] (--tx-in TX-IN
          [--tx-in-script-file FILE
            [(--tx-in-datum-file FILE | --tx-in-datum-value JSON VALUE)
              (--tx-in-redeemer-file FILE | --tx-in-redeemer-value JSON VALUE)
              --tx-in-execution-units (INT, INT)]]) [--tx-in-collateral TX-IN]
          [--tx-out ADDRESS VALUE [--tx-out-datum-hash HASH]]
          [--mint VALUE (--mint-script-file FILE
            [(--mint-redeemer-file FILE | --mint-redeemer-value JSON VALUE)
              --mint-execution-units (INT, INT)])] [--invalid-before SLOT]
          [--invalid-hereafter SLOT] [--fee LOVELACE]
          [--certificate-file CERTIFICATEFILE
            [--certificate-script-file FILE
              [
                (--certificate-redeemer-file FILE |
                  --certificate-redeemer-value JSON VALUE)
                --certificate-execution-units (INT, INT)]]]
          [--withdrawal WITHDRAWAL
            [--withdrawal-script-file FILE
              [
                (--withdrawal-redeemer-file FILE |
                  --withdrawal-redeemer-value JSON VALUE)
                --withdrawal-execution-units (INT, INT)]]]
          [--json-metadata-no-schema | --json-metadata-detailed-schema]
          [--auxiliary-script-file FILE]
          [--metadata-json-file FILE | --metadata-cbor-file FILE]
          [--genesis FILE | --protocol-params-file FILE]
          [--update-proposal-file FILE] --out-file FILE
```

**Comment by HuwCampbell** [comment]
I'll have a look John

**Comment by HuwCampbell** [comment]
I've whipped up something to this end which just does "the right thing" without requiring config.

Namely, if the pretext is longer than some number (35 or something) **and** the rest of the usage text won't fit on the same line; it will insert a line break and nest the rest.

**Comment by newhoggy** [comment]
Thanks!  If you have a branch, I can take it for a test drive.

**Comment by HuwCampbell** [comment]
https://github.com/pcapriotti/optparse-applicative/tree/topic/overflow

**Comment by newhoggy** [comment]
Yep!  Much better:

```
cardano-cli) transaction build-raw
Usage: cardano-cli transaction build-raw
         [--byron-era | --shelley-era | --allegra-era | --mary-era |
           --alonzo-era] (--tx-in TX-IN
         [--tx-in-script-file FILE
           [(--tx-in-datum-file FILE | --tx-in-datum-value JSON VALUE)
             (--tx-in-redeemer-file FILE | --tx-in-redeemer-value JSON VALUE)
             --tx-in-execution-units (INT, INT)]]) [--tx-in-collateral TX-IN]
         [--tx-out ADDRESS VALUE [--tx-out-datum-hash HASH]]
         [--mint VALUE (--mint-script-file FILE
           [(--mint-redeemer-file FILE | --mint-redeemer-value JSON VALUE)
             --mint-execution-units (INT, INT)])] [--invalid-before SLOT]
         [--invalid-hereafter SLOT] [--fee LOVELACE]
         [--certificate-file CERTIFICATEFILE
           [--certificate-script-file FILE
             [
               (--certificate-redeemer-file FILE |
                 --certificate-redeemer-value JSON VALUE)
               --certificate-execution-units (INT, INT)]]]
         [--withdrawal WITHDRAWAL
           [--withdrawal-script-file FILE
             [
               (--withdrawal-redeemer-file FILE |
                 --withdrawal-redeemer-value JSON VALUE)
               --withdrawal-execution-units (INT, INT)]]]
         [--json-metadata-no-schema | --json-metadata-detailed-schema]
         [--auxiliary-script-file FILE]
         [--metadata-json-file FILE | --metadata-cbor-file FILE]
         [--genesis FILE | --protocol-params-file FILE]
         [--update-proposal-file FILE] --out-file FILE
```

**Comment by newhoggy** [comment]
And this is what a smaller command looks like:

```
Usage: cardano-cli address key-gen [--normal-key | --extended-key | --byron-key]
                                   --verification-key-file FILE
                                   --signing-key-file FILE

  Create an address key pair.
```

**Comment by HuwCampbell** [comment]
I've a PR up in #439 to implement a simpler set of changes.

As discussed in #428, I'll close this one now, and we can redirect comments regarding rendering there.

Thanks!

**Pull request closed without merging**
