### PR TITLE
fix missing imports in README.md

### PR DESCRIPTION
**Pull request by yuhangwang**
fix missing imports in the example from the README.md

### CODE REVIEW

**Comment by HuwCampbell** [comment]
Hey, thanks for this.
A few comments,  `Data.Semigroup` would be better, as it won't break when 8.2 comes along, and qualified import don't require documentation.
Cheers,
Huw

**Comment by yuhangwang** [comment]
Thanks for the tip!

**Comment by HuwCampbell** [comment]
Heh,
The M doesn't refer to the thing being repeated, but that it's repeating an "Monadic" action. It should actually be `replicateM_` from `Control.Monad` though. That section of the README was added in separate PR a few days ago and I didn't notice that the function name was incorrect.
Huw

**Comment by HuwCampbell** [comment]
Have done the fix ups and rebased your PR. Thanks!

**Pull request closed without merging**
