### PR TITLE
docs: remove broken link

### PR DESCRIPTION
**Pull request by xieyuschen**
The matrix link is broken like this, shall we remove it?
image

### CODE REVIEW

**Comment by xieyuschen** [comment]
Hi @pcapriotti , could you kindly check this PR?

**Comment by HuwCampbell** [comment]
Sorry I'm just on holiday. Back next week.

**Comment by xieyuschen** [comment]
> Sorry I'm just on holiday. Back next week.

I see. Have a nice holiday:)

**Comment by HuwCampbell** [comment]
Ta

**Pull request merged**
