### PR TITLE
Fix GHC 7.10 warnings.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by sjakobi** [comment]
There's an alternative to CPP for fixing these redundant import warnings.

Hypothetical example:
```haskell
import Control.Applicative (Applicative(..))
import Data.Monoid (<>)
```

Fixed:
```haskell
import Control.Applicative
import Data.Monoid
import Prelude
```

Yes, this solution relies on a quirk in GHC, but it's somewhat cleaner and possibly easier to maintain than the CPP-based solution.

There's a bit more information on this trick in this [ghc-dev thread](https://mail.haskell.org/pipermail/ghc-devs/2015-February/008425.html).

**Comment by HuwCampbell** [comment]
I'm keen on getting this right... will look into it.

**Comment by HuwCampbell** [comment]
Thanks, another branch was opened with the `import Prelude` option which seemed neater to me. Therefore I'll close this PR.

Still much appreciated.

**Comment by sjakobi** [comment]
> Thanks, another branch was opened with the import Prelude option which seemed neater to me.

Yes, that's the cleaner solution.

**Pull request closed without merging**
