### PR TITLE
Allow more complex usage of many and some.

### PR DESCRIPTION
**Pull request by HuwCampbell**
Previously the entire BindP was required to pass during each call to
searchParser. Meaning that many pairs of arguments were not possible. By
being a bit more lazy in progressing through these options, and rebuilding
the BindP instead of asserting that it must be complete, we can allow for
many pairs or n-tuples (or other complex constructed datatypes) of items.

For example:
```haskell
p = many $ (,) <$> argument str idm <*> argument str idm
```

### CODE REVIEW

**Comment by ibotty** [comment]
One thing that could be enhanced is the usage help.

For `many $ (,) <$> option str (short 'a') <*> option str (short 'b')` it will yield

    Usage: <program> [-a ARG] [-b ARG]

I would expect

    Usage <program> [-a ARG [-b ARG]]...

because the the options are dependent. (The `...` part is of course a different feature request.)

**Comment by HuwCampbell** [comment]
Thanks, glad I could help. More tests are always welcome.

Yep, I'm aware of the usage text issues. It will require a bit more work still, as the current `OptTree` type is not designed to handle cases like these.

**Comment by HuwCampbell** [comment]
Closing as this PR is not over master

**Comment by ibotty** [comment]
Sorry for being a little dense. Is it merged? I tested this patch in a program of mine and it works wonderfully.

**Comment by ibotty** [comment]
The answer is yes. Thank you for the prompt patch!

**Pull request closed without merging**
