### PR TITLE
Allow inlining of subparsers instead of independent execution

### PR DESCRIPTION
**Pull request by HuwCampbell**

### CODE REVIEW

**Comment by domenkozar** [comment]
Does this also address https://github.com/pcapriotti/optparse-applicative/issues/294?

**Comment by HuwCampbell** [comment]
At the moment no.

That said, as it'll be possible to mix them with this flag on, it might make sense to support it. Essentially, it requires pushing into a context IFF the inline path is activated *after* `searchArg` has run.

**Comment by jkachmar** [comment]
Is there anything preventing this from being merged? I just tested this branch and it solves a UX pain point in an application I'm working on quite nicely.

**Comment by matthew-piziak** [comment]
Also looking forward to this.

**Comment by HuwCampbell** [comment]
I'll include it in the next version (after a bit more testing in real projects).

**Comment by domenkozar** [comment]
It would be lovely to have this out :)

**Comment by jkachmar** [comment]
We’ve been using it in a production application since October without any ill-effect, if that bit of anecdata counts for anything :)

**Pull request merged**
